name: dpaperback_cli
description: A commandline tool for bundling and serving Paperback written in Dart.
version: 1.0.0
homepage: https://github.com/getBoolean/dart_pb_cli

publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

executables:
  dpaperback:

dependencies:
  dart_pb_extensions_common:
    git: https://github.com/getBoolean/dart_pb_extensions_common
  dcli: ^1.36.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
