name: dpaperback_cli
description: A commandline tool for bundling and serving Paperback written in Dart.
version: 1.0.0
homepage: https://github.com/getBoolean/dpaperback_cli/

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  dpaperback:

dependencies:
  archive: ^3.3.5
  args: ^2.3.1
  cli_completion: ^0.1.0+1
  console: ^4.1.0
  dart_pb_extensions_common:
    git: https://github.com/getBoolean/dart_pb_extensions_common
  dcli: ^1.36.0
  puppeteer: ^2.19.0
  riverpod: ^2.1.1
  shelf: ^1.4.0
  shelf_static: ^1.1.1
  stream_transform: ^2.1.0
  watcher: ^1.0.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
